const CACHE_PREFIX='mundo-sarah-';
const CACHE_NAME=`${CACHE_PREFIX}v31-range-safe`;
const SCRIPTS=['sim-life.js','city-progress-v10.js','routine-v11.js','pet-care-v12.js','home-care-v13.js','room-explore-v14.js','city-journal-v15.js','home-objects-v16.js','decor-studio-v17.js','needs-guide-v18.js','magic-hub-v30.js','magic-salon-v30.js','magic-wardrobe-v30.js','magic-games-v30.js','magic-patch-v30.js'];
const APP_SHELL=['./','./index.html','./mundo-magico.html','./amizades.html','./manifest.webmanifest','./icon-192.svg','./icon-512.svg','./icon-512-maskable.svg',...SCRIPTS.map(x=>'./'+x)];
const PRIVATE_PATHS=['/api/','/auth','/login','/logout','/admin','/session','/token','/password','/account','/profile'];
const SENSITIVE_QUERY_KEYS=['token','access_token','refresh_token','password','secret','session','auth','authorization','api_key','apikey','key','code','credential'];
const SHELL_PATHS=new Set(APP_SHELL.map(path=>new URL(path,self.registration.scope).pathname));
function hasSensitiveQuery(url){for(const key of url.searchParams.keys())if(SENSITIVE_QUERY_KEYS.includes(key.toLowerCase()))return true;return false}
function safe(response){if(!response||!response.ok||response.status===206||response.type==='opaque')return false;const cc=(response.headers.get('cache-control')||'').toLowerCase();if(cc.includes('no-store')||cc.includes('private')||response.headers.has('set-cookie')||response.headers.has('content-range'))return false;const vary=(response.headers.get('vary')||'').toLowerCase();return !vary.split(',').map(v=>v.trim()).some(v=>v==='*'||v==='cookie'||v==='authorization'||v==='range'||v==='if-range')}
async function precache(){const cache=await caches.open(CACHE_NAME);await Promise.all(APP_SHELL.map(async path=>{try{const req=new Request(path,{credentials:'omit',cache:'reload'}),res=await fetch(req);if(safe(res))await cache.put(req,res.clone())}catch(e){console.warn('[Mundo da Sarah] cache ignorado:',path,e)}}))}
self.addEventListener('install',e=>{e.waitUntil(precache());self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith(CACHE_PREFIX)&&k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim()})())});
async function inject(response){if(!response||!response.ok)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let text=await response.text();for(const src of SCRIPTS)if(!text.includes(src))text=text.replace('</body>',`<script src="./${src}"></script></body>`);return new Response(text,{status:response.status,statusText:response.statusText,headers:response.headers})}
async function cached(path){const cache=await caches.open(CACHE_NAME);return cache.match(new Request(path,{credentials:'omit'}),{ignoreSearch:true})}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;if(PRIVATE_PATHS.some(p=>url.pathname.toLowerCase().includes(p)))return;if(req.headers.has('authorization')||req.headers.has('cookie')||req.headers.has('range')||req.headers.has('if-range')||hasSensitiveQuery(url))return;if(req.mode==='navigate'){event.respondWith((async()=>{const friends=url.pathname.endsWith('amizades.html'),magic=url.pathname.endsWith('mundo-magico.html');try{const fresh=await fetch(req,{cache:'no-store'});return friends?fresh:inject(fresh)}catch{const fb=await cached(friends?'./amizades.html':magic?'./mundo-magico.html':'./index.html');if(fb)return friends?fb:inject(fb);return new Response('Sem conexão. Reconecte-se para continuar.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}})}})());return}if(url.search||!SHELL_PATHS.has(url.pathname))return;event.respondWith((async()=>{const cache=await caches.open(CACHE_NAME),hit=await cache.match(req,{ignoreSearch:true});if(hit)return hit;const res=await fetch(new Request(req,{credentials:'omit'}));if(safe(res))await cache.put(req,res.clone());return res})())});